# Generated by Django 5.2.12 on 2026-04-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
