# Generated by Django 5.2.12 on 2026-05-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created Job', 'Created Job'), ('Updated Job', 'Updated Job'), ('Deleted Job', 'Deleted Job'), ('Applied', 'Applied'), ('Shortlisted Candidate', 'Shortlisted Candidate'), ('Rejected Candidate', 'Rejected Candidate'), ('Scheduled Interview', 'Scheduled Interview')], max_length=100)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
