# Generated by Django 5.2.12 on 2026-05-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidateprofile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
