# Generated by Django 5.2.12 on 2026-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidateprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
